version: "3.9"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"

  nginx:
    image: nginx:alpine

    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - frontend-build:/usr/share/nginx/html
    depends_on:
      - frontend

volumes:
  frontend-build:
